version: "2"
services:
  zookeeper-grpc:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

  kafka-grpc:
    image: wurstmeister/kafka:0.10.0.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-grpc:2181"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper-grpc
